### ISSUE TITLE
Prepare file with an empty array

### ISSUE THREAD

**Issue by Zawuza** [viant/dsunit#13]
Hello!

I encountered an issue with prepare files when using golang 1.12.3 and PostgreSQL 9.6.11.

I expect that when I have `[]` in my "case_prepare_table.json" dsunit will make all tables that were created in "InitFromURL" call empty or leave them empty in case they are already in this state.

Now I have the following problem. For my tests I have a following init.yaml file:
```
Datastore: datastorename
Config:
  DriverName: postgres
  Descriptor: host=... port=5432 user=... password=... dbname=datastorename sslmode=disable
Admin:
  Datastore: postgres
  Config:
    DriverName: postgres
    Descriptor: host=... port=5432 user=... password=... dbname=postgres sslmode=disable
Recreate: true
Scripts:
  - URL: newdb.sql
```
It means that before each test whole database will be dropped and the SQL script will be executed that creates tables I need. Now assume that my "test_case_prepare_table.json" looks as follows:
`[]`
In my test I have the following line: 
```
if !dsunit.PrepareFor(t, "datastorename", "testdata_folder", "test_case") {
  t.Fatal("Preparation for the test failed")
}
```
What happens is that test fails here, because PrepareFor returns false. Log also shows the following exception:
`pq: Could not complete operation in a failed transaction`
This doesn't look like intended behavior.

Regards
Andrei
